"""
Reglas de negocio: qué campos son OBLIGATORIOS, OPCIONALES o NO_NECESARIOS
según el tipo de diagnóstico seleccionado.

Esta es la ÚNICA fuente de verdad para esta lógica. El frontend la consulta
vía el endpoint /api/reglas para pintar el formulario dinámicamente, y el
backend la vuelve a usar para validar antes de guardar (nunca confiamos
solo en la validación del navegador).
"""

# Niveles posibles para cada campo
OBLIGATORIO = "OBLIGATORIO"
OPCIONAL = "OPCIONAL"
NO_NECESARIO = "NO_NECESARIO"

DIAGNOSTICOS_DISPONIBLES = [
    "HASHBOARD",
    "CONTROL BOARD",
    "PSU DEAD",
    "PSU DEFICIENT",
    "MULTIPLE HASHBOARD",
    "PSU AND HASHBOARD",
    "PSU AND CONTROL BOARD",
    "UNKNOW",
    "LEAKEGE",
]

# Campos base que existen siempre (independiente del diagnóstico)
TODOS_LOS_CAMPOS = [
    "PLATAFORMA", "CONTENEDOR", "RACK", "FILA", "COLUMNA", "DIAGNOSTICO",
    "IP", "SN_DIGITAL", "SN_FISICA", "MAC", "MODELO", "TIPO_PIEZA",
    "PSU_SN", "CHAIN_0", "CHAIN_1", "CHAIN_2", "FUGA", "ESTADO",
    "SUPERVISOR", "OBSERVACION",
]

# Matriz de reglas: para cada diagnóstico, el nivel de cada campo.
REGLAS_POR_DIAGNOSTICO = {
    "HASHBOARD": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": OBLIGATORIO, "SN_DIGITAL": OBLIGATORIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": NO_NECESARIO,
        "PSU_SN": NO_NECESARIO, "CHAIN_0": OPCIONAL, "CHAIN_1": OPCIONAL,
        "CHAIN_2": OPCIONAL, "FUGA": NO_NECESARIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OBLIGATORIO,
    },
    "CONTROL BOARD": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": NO_NECESARIO, "SN_DIGITAL": NO_NECESARIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": NO_NECESARIO,
        "PSU_SN": NO_NECESARIO, "CHAIN_0": NO_NECESARIO, "CHAIN_1": NO_NECESARIO,
        "CHAIN_2": NO_NECESARIO, "FUGA": NO_NECESARIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OPCIONAL,
    },
    "PSU DEAD": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": NO_NECESARIO, "SN_DIGITAL": NO_NECESARIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": OBLIGATORIO,
        "PSU_SN": OBLIGATORIO, "CHAIN_0": NO_NECESARIO, "CHAIN_1": NO_NECESARIO,
        "CHAIN_2": NO_NECESARIO, "FUGA": NO_NECESARIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OPCIONAL,
    },
    "PSU DEFICIENT": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": OBLIGATORIO, "SN_DIGITAL": OBLIGATORIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": OBLIGATORIO,
        "PSU_SN": OBLIGATORIO, "CHAIN_0": NO_NECESARIO, "CHAIN_1": NO_NECESARIO,
        "CHAIN_2": NO_NECESARIO, "FUGA": NO_NECESARIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OBLIGATORIO,
    },
    "MULTIPLE HASHBOARD": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": OBLIGATORIO, "SN_DIGITAL": OBLIGATORIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": NO_NECESARIO,
        "PSU_SN": NO_NECESARIO, "CHAIN_0": OPCIONAL, "CHAIN_1": OPCIONAL,
        "CHAIN_2": OPCIONAL, "FUGA": NO_NECESARIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OPCIONAL,
    },
    "PSU AND HASHBOARD": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": OBLIGATORIO, "SN_DIGITAL": OBLIGATORIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": OBLIGATORIO,
        "PSU_SN": OBLIGATORIO, "CHAIN_0": OPCIONAL, "CHAIN_1": OPCIONAL,
        "CHAIN_2": OPCIONAL, "FUGA": NO_NECESARIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OPCIONAL,
    },
    "PSU AND CONTROL BOARD": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": NO_NECESARIO, "SN_DIGITAL": NO_NECESARIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": OBLIGATORIO,
        "PSU_SN": OBLIGATORIO, "CHAIN_0": NO_NECESARIO, "CHAIN_1": NO_NECESARIO,
        "CHAIN_2": NO_NECESARIO, "FUGA": NO_NECESARIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OPCIONAL,
    },
    "UNKNOW": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": OPCIONAL, "SN_DIGITAL": OPCIONAL, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": OPCIONAL,
        "PSU_SN": OPCIONAL, "CHAIN_0": OPCIONAL, "CHAIN_1": OPCIONAL,
        "CHAIN_2": OPCIONAL, "FUGA": OPCIONAL, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OBLIGATORIO,
    },
    "LEAKEGE": {
        "PLATAFORMA": OBLIGATORIO, "CONTENEDOR": OBLIGATORIO, "RACK": OBLIGATORIO,
        "FILA": OBLIGATORIO, "COLUMNA": OBLIGATORIO, "DIAGNOSTICO": OBLIGATORIO,
        "IP": NO_NECESARIO, "SN_DIGITAL": NO_NECESARIO, "SN_FISICA": OBLIGATORIO,
        "MAC": OBLIGATORIO, "MODELO": OBLIGATORIO, "TIPO_PIEZA": NO_NECESARIO,
        "PSU_SN": NO_NECESARIO, "CHAIN_0": NO_NECESARIO, "CHAIN_1": NO_NECESARIO,
        "CHAIN_2": NO_NECESARIO, "FUGA": OBLIGATORIO, "ESTADO": OBLIGATORIO,
        "SUPERVISOR": OBLIGATORIO, "OBSERVACION": OPCIONAL,
    },
}


def obtener_reglas(diagnostico: str) -> dict:
    """Devuelve el diccionario de reglas {campo: nivel} para un diagnóstico dado."""
    if diagnostico not in REGLAS_POR_DIAGNOSTICO:
        raise ValueError(f"Diagnóstico desconocido: {diagnostico}")
    return REGLAS_POR_DIAGNOSTICO[diagnostico]


def campos_obligatorios(diagnostico: str) -> list:
    reglas = obtener_reglas(diagnostico)
    return [campo for campo, nivel in reglas.items() if nivel == OBLIGATORIO]
